language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1

addons:
  apt:
    packages:
      - ca-certificates

script: "bundle exec rake test"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
