# To emulate the GitHub Pages environment
safe: true
lsi: false

# To prevent Jekyll from reading bundles on Travis CI
exclude: [vendor]
markdown: redcarpet
highlighter: pygments
repository: https://github.com/connectbot/connectbot/
permalink: pretty
gems:
  - jekyll-sitemap
